[package]
name = "ch17-macro"
version = "0.1.0"
authors = ["Johny.li <johny.li@selmit.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
